packageExtensions:
  posthtml-component@*:
    dependencies:
      posthtml: "*"
  posthtml-expressions@*:
    dependencies:
      posthtml: "*"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
enableGlobalCache: false
